<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Onumia\\Lib\\Pitmaster\\' => array($vendorDir . '/pitmaster/pitmaster/src'),
    'Onumia\\Lib\\PhpParser\\' => array($vendorDir . '/nikic/php-parser/lib/PhpParser'),
    'Onumia\\Lib\\Inline0\\WordPressLicensedUpdater\\' => array($vendorDir . '/inline0/wordpress-licensed-updater/src'),
    'Onumia\\Lib\\Inline0\\WordPressGitHubUpdater\\' => array($vendorDir . '/inline0/wordpress-github-updater/src'),
);
